version: "3.1"
services:
  backend:
    build: ./backend
    image: "learning-backend:1.0.0"
    container_name: backend
    ports:
      - '4000:4000'
    volumes:
      - /mnt/d/projects/learning/backend:/app:ro
