version: "3.1"
services:
  backend:
    build: ./backend
    image: "learning-backend:1.0.0"
    container_name: backend
    ports:
      - '4000:4000'
    volumes:
      - /mnt/d/projects/learning/backend:/app:ro
  frontend:
    build: ./frontend
    image: "learning-frontend:1.0.0"
    container_name: frontend
    ports:
      - '3000:3000'
    volumes:
      - /mnt/d/projects/learning/frontend:/app/frontend:ro
    stdin_open: true
    tty: true
