version: "3.9"
services:
  mongodb:
    image: mongo
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - "27017:27017"
    volumes:
      - /mnt/d/projects/learning/data:/data/db:rw
  # mongo-express:
  #   image: mongo-express
  #   restart: always
  #   container_name: mongo-express
  #   environment:
  #     - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
  #     - ME_CONFIG_MONGODB_ADMINPASSWORD=password
  #     - ME_CONFIG_MONGODB_SERVER=mongodb
  #   ports:
  #     - "8081:8081"
  # backend:
  #   build: ./backend
  #   image: "learning-backend:1.0.0"
  #   container_name: backend
  #   ports:
  #     - '4000:4000'
  #   volumes:
  #     - /mnt/d/projects/learning/backend:/app:ro
